// prisma/seed.ts
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  // Engineers
  await prisma.engineer.createMany({
    data: [
      {
        name: "Б. Батжаргал",
        email: "bat@mine.mn",
        passwordHash: await bcrypt.hash("password123", 10),
      },
      {
        name: "Э. Оюунбаяр",
        email: "oyun@mine.mn",
        passwordHash: await bcrypt.hash("password456", 10),
      },
    ],
    skipDuplicates: true,
  });
  console.log("✓ Engineers seeded");

  // Departments + Questions
  const departments = [
    {
      name: "1001",
      questions: [
        {
          title: "1001-BN-001",
          type: "TEXT",
          order: 1,
          label: "Хүдэр дамжуулах бункерийн  түвшин, %",
        },
        {
          title: "1001-BN-002",
          type: "TEXT",
          order: 2,
          label: "Хүдэр дамжуулах бункерийн  түвшин, %",
        },
        {
          title: "1001-FE-001",
          type: "TEXT",
          order: 3,
          label: "Хавтан тэжээгчийн хурд, Hz",
        },
        {
          title: "1001-FE-002",
          type: "TEXT",
          order: 4,
          label: "Хавтан тэжээгчийн хурд, Hz",
        },
        {
          title: "1001-BN-003",
          type: "TEXT",
          order: 9,
          label: "Бутлагдсан хүдрийн бункерийн түвшин, %",
        },
        {
          title: "1001-BN-004",
          type: "TEXT",
          order: 10,
          label: "Бутлагдсан хүдрийн бункерийн түвшин, %",
        },
        {
          title: "1001-FE-003",
          type: "TEXT",
          order: 11,
          label: "Хавтан тэжээгчийн хурд%",
        },
        {
          title: "1001-FE-004",
          type: "TEXT",
          order: 12,
          label: "Хавтан тэжээгчийн хурд%",
        },
        {
          title: "Хүдрийн овоолго хийсэн эсэх",
          type: "BOOLEAN",
          order: 14,
          label: null,
        },
        {
          title: "шанаганы тоогоор LG",
          type: "TEXT",
          order: 15,
          label: "Үйлдвэр тэжээсэн хүдрийн харьцаа",
          allowedHours: [5, 17],
        },
        {
          title: "шанаганы тоогоор MG",
          type: "TEXT",
          order: 16,
          label: "Үйлдвэр тэжээсэн хүдрийн харьцаа",
          allowedHours: [5, 17],
        },
        {
          title: "шанаганы тоогоор LG",
          type: "TEXT",
          order: 17,
          label: "Үйлдвэр тэжээсэн хүдрийн харьцаа",
          allowedHours: [5, 17],
        },
        {
          title: "Нөөцөлсөн шанаганы тоо",
          type: "TEXT",
          order: 18,
          label: null,
          allowedHours: [5, 17],
        },
        {
          title: "Нөөцөөс тэжээсэн шанаганы тоо",
          type: "TEXT",
          order: 19,
          label: null,
          allowedHours: [5, 17],
        },
        {
          title: "Нэмэлт мэдээлэл",
          type: "TEXT",
          order: 20,
          label: null,
        },
      ],
    },
    {
      name: "1002",
      questions: [
        // Every hour
        {
          title: "Үзүүлэлт",
          type: "TEXT",
          order: 1,
          label: "Жин хэмжигч",
          allowedHours: [],
        },
        {
          title: "Бүтээл, т/цаг",
          type: "TEXT",
          order: 2,
          label: "Жин хэмжигч",
          allowedHours: [],
        },
        {
          title: "Apron Feeder#003-ын хурд, %",
          type: "TEXT",
          order: 3,
          label: "Хагас өөрөө нунтаглах тээрэм",
          allowedHours: [],
        },
        {
          title: "Чадал, Квт",
          type: "TEXT",
          order: 4,
          label: "Хагас өөрөө нунтаглах тээрэм",
          allowedHours: [],
        },
        {
          title: "Гаралтын хатуулаг, %",
          type: "TEXT",
          order: 5,
          label: "Хагас өөрөө нунтаглах тээрэм",
          allowedHours: [],
        },
        {
          title: "1002-SC-002 доод бүтээгдэхүүний хатуулаг, %",
          type: "TEXT",
          order: 6,
          label: "Хагас өөрөө нунтаглах тээрэм",
          allowedHours: [],
        },
        {
          title: "1002-РР-001 хурд, %",
          type: "TEXT",
          order: 7,
          label: "Хагас өөрөө нунтаглах тээрэм",
          allowedHours: [],
        },
        {
          title: "1002-РР-002 хурд, %",
          type: "TEXT",
          order: 8,
          label: "Хагас өөрөө нунтаглах тээрэм",
          allowedHours: [],
        },
        {
          title: "Чадал, кВт",
          type: "TEXT",
          order: 10,
          label: "Бөөрөнцөгт тээрэм",
          allowedHours: [],
        },
        {
          title: "Гаралтын хатуулаг, % (БТ)",
          type: "TEXT",
          order: 11,
          label: "Бөөрөнцөгт тээрэм",
          allowedHours: [],
        },

        // Only odd hours: 9,11,13,15,17,19,21,23,1,3,5
        {
          title:
            "Гидроциклоны дээд бүтээгдэхүүний урсгал хэмжигчийн заалт, м3/ц ",
          type: "TEXT",
          order: 12,
          label: "Бөөрөнцөгт тээрэм",
          allowedHours: [9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },

        // Every hour
        {
          title: "1002-РР-003 хурд, %",
          type: "TEXT",
          order: 13,
          label: "Бөөрөнцөгт тээрэм",
          allowedHours: [],
        },
        {
          title: "1002-РР-004 хурд, %",
          type: "TEXT",
          order: 14,
          label: "Бөөрөнцөгт тээрэм",
          allowedHours: [],
        },
        {
          title: "Дээд бүтээгдэхүүний 75 микрон, %",
          type: "TEXT",
          order: 15,
          label: "Гидроциклон",
          allowedHours: [],
        },
        {
          title: "Доод бүтээгдэхүүний хатуулаг, %",
          type: "TEXT",
          order: 16,
          label: "Гидроциклон",
          allowedHours: [],
        },

        // Only odd hours: 7,9,11,13,15,17,19,21,23,1,3,5
        {
          title: "Дээд бүтээгдэхүүний хатуулаг 75 микрон, %",
          type: "TEXT",
          order: 17,
          label: "Гидроциклон",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },

        // Every even hour: 6,8,10,12,14,16,18,20,22,0,2,4
        {
          title: "Гидроциклон-1",
          type: "BOOLEAN",
          order: 18,
          label: "Гидроциклон",
          allowedHours: [],
        },
        {
          title: "Гидроциклон-2",
          type: "BOOLEAN",
          order: 19,
          label: "Гидроциклон",
          allowedHours: [],
        },
        {
          title: "Гидроциклон-3",
          type: "BOOLEAN",
          order: 20,
          label: "Гидроциклон",
          allowedHours: [],
        },
        {
          title: "Гидроциклон-4",
          type: "BOOLEAN",
          order: 21,
          label: "Гидроциклон",
          allowedHours: [],
        },
        {
          title: "Гидроциклон-5",
          type: "BOOLEAN",
          order: 22,
          label: "Гидроциклон",
          allowedHours: [],
        },
        {
          title: "Гидроциклон-6",
          type: "BOOLEAN",
          order: 23,
          label: "Гидроциклон",
          allowedHours: [],
        },
        {
          title: "Гидроциклон-7",
          type: "BOOLEAN",
          order: 24,
          label: "Гидроциклон",
          allowedHours: [],
        },

        // Every hour
        {
          title: "Даралт",
          type: "TEXT",
          order: 25,
          label: "Гидроциклон",
          allowedHours: [],
        },

        // Every even hour: 6,8,10,12,14,16,18,20,22,0,2,4
        {
          title: "3001-ТК-001 ус, %",
          type: "TEXT",
          order: 26,
          label: "Усны танкууд",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "3001-ТК-002 ус, %",
          type: "TEXT",
          order: 27,
          label: "Усны танкууд",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "3002-ТК-001 ус, %",
          type: "TEXT",
          order: 28,
          label: "Усны танкууд",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "3003-ТК-001 ус, %",
          type: "TEXT",
          order: 29,
          label: "Усны танкууд",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "ХӨН тээрмийн тэжээлийн ус, м3",
          type: "TEXT",
          order: 30,
          label: null,
          allowedHours: [5, 17],
        },
        {
          title: "Бөөрөнцөгт тээрмийн тэжээлийн ус, м3",
          type: "TEXT",
          order: 31,
          label: null,
          allowedHours: [5, 17],
        },
        {
          title: "ХӨН тээрмийн скат, шанага",
          type: "TEXT",
          order: 32,
          label: null,
          allowedHours: [5, 17],
        },
        {
          title: "Бөөрөнцөгт тээрмийн скат, шанага ",
          type: "TEXT",
          order: 33,
          label: null,
          allowedHours: [5, 17],
        },
        {
          title: "Цаг",
          type: "TEXT",
          order: 34,
          label: "ХӨН тээрэмд нэмсэн ган бөөрөнцөг",
        },
        {
          title: "Хэмжээ мм",
          type: "NUMBER",
          order: 35,
          label: "ХӨН тээрэмд нэмсэн ган бөөрөнцөг",
        },
        {
          title: "Жин тн",
          type: "NUMBER",
          order: 36,
          label: "ХӨН тээрэмд нэмсэн ган бөөрөнцөг",
        },
        {
          title: "Цаг",
          type: "TEXT",
          order: 37,
          label: "Бөмбөлөгт тээрэмд нэмсэн ган бөөрөнцөг",
        },
        {
          title: "Хэмжээ мм",
          type: "NUMBER",
          order: 38,
          label: "Бөмбөлөгт тээрэмд нэмсэн ган бөөрөнцөг",
        },
        {
          title: "Жин тн",
          type: "NUMBER",
          order: 39,
          label: "Бөмбөлөгт тээрэмд нэмсэн ган бөөрөнцөг",
        },
        {
          title: "Нэмэлт мэдээлэл",
          type: "TEXT",
          order: 40,
          label: null,
        },
      ],
    },
    {
      name: "1006 1007",
      questions: [
        // === 1006-TH-001 Өтгөрүүлэгч ===
        {
          title: "Гаралтын 74 мкм %",
          type: "TEXT",
          order: 1,
          label: "1006-TH-001 Өтгөрүүлэгч",
          allowedHours: [],
        },
        {
          title: "Гаралтын хатуулаг %",
          type: "TEXT",
          order: 2,
          label: "1006-TH-001 Өтгөрүүлэгч",
          allowedHours: [],
        },
        {
          title: "Халианы усны насосны хурд, %",
          type: "TEXT",
          order: 3,
          label: null,
          allowedHours: [],
        },
        {
          title: "Гаралтын насосны хурд, %",
          type: "TEXT",
          order: 4,
          label: null,
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "PH зоондын заалт",
          type: "TEXT",
          order: 5,
          label: null,
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Bed mass sensor, kPa",
          type: "TEXT",
          order: 6,
          label: null,
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Bed level sensor, м",
          type: "TEXT",
          order: 7,
          label: null,
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Мушгилтын момент, mPa",
          type: "TEXT",
          order: 8,
          label: null,
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Флокулянтын процент, %",
          type: "TEXT",
          order: 9,
          label: null,
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Флокулянтын дозын насосын хурд, %",
          type: "TEXT",
          order: 10,
          label: null,
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Шохойн урсгал, м3/цаг",
          type: "TEXT",
          order: 11,
          label: null,
          allowedHours: [],
        },
        {
          title: "Халианы усны FreeCN, ppm",
          type: "TEXT",
          order: 12,
          label: null,
          allowedHours: [],
        },
        {
          title: "Халианы усны pH",
          type: "TEXT",
          order: 13,
          label: null,
          allowedHours: [],
        },
        // === Уусгалтын танк#1 ===
        {
          title: "Гар PH метрийн заалт",
          type: "TEXT",
          order: 14,
          label: "Уусгалтын танк#1",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 15,
          label: "Уусгалтын танк#1",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 16,
          label: "Уусгалтын танк#1",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 17,
          label: "Уусгалтын танк#1",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "NaCN урсгал, м3/цаг",
          type: "TEXT",
          order: 18,
          label: "Уусгалтын танк#1",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "HCN детекторын заалт",
          type: "TEXT",
          order: 19,
          label: "Уусгалтын танк#1",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        // === Уусгалтын танк#2 ===
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 22,
          label: "Уусгалтын танк#2",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        // === Уусгалтын танк#3 ===
        {
          title: "pH",
          type: "TEXT",
          order: 23,
          label: "Уусгалтын танк#3",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 24,
          label: "Уусгалтын танк#3",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 25,
          label: "Уусгалтын танк#3",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 26,
          label: "Уусгалтын танк#3",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        // === Уусгалтын танк#4 ===
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 27,
          label: "Уусгалтын танк#4",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 28,
          label: "Уусгалтын танк#4",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 29,
          label: "Уусгалтын танк#4",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        {
          title: "Гар PH метрийн заалт",
          type: "TEXT",
          order: 30,
          label: "Уусгалтын танк#4",
          allowedHours: [7, 9, 11, 13, 15, 17, 19, 21, 23, 1, 3, 5],
        },
        // === Шингээлтийн танк#1 ===
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 31,
          label: "Шингээлтийн танк#1",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 32,
          label: "Шингээлтийн танк#1",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 33,
          label: "Шингээлтийн танк#1",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Нүүрсний хэмжээ, гр/л",
          type: "TEXT",
          order: 34,
          label: "Шингээлтийн танк#1",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        // === Шингээлтийн танк#2 ===
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 35,
          label: "Шингээлтийн танк#2",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 36,
          label: "Шингээлтийн танк#2",
          allowedHours: [],
        },
        {
          title: "Нүүрсний хэмжээ, гр/л",
          type: "TEXT",
          order: 37,
          label: "Шингээлтийн танк#2",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        // === Шингээлтийн танк#3 ===
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 38,
          label: "Шингээлтийн танк#3",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 39,
          label: "Шингээлтийн танк#3",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Нүүрсний хэмжээ, гр/л",
          type: "TEXT",
          order: 40,
          label: "Шингээлтийн танк#3",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        // === Шингээлтийн танк#4 ===
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 41,
          label: "Шингээлтийн танк#4",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 42,
          label: "Шингээлтийн танк#4",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 43,
          label: "Шингээлтийн танк#4",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Нүүрсний хэмжээ, гр/л",
          type: "TEXT",
          order: 44,
          label: "Шингээлтийн танк#4",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        // === Шингээлтийн танк#5 ===
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 45,
          label: "Шингээлтийн танк#5",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 46,
          label: "Шингээлтийн танк#5",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Нүүрсний хэмжээ, гр/л",
          type: "TEXT",
          order: 47,
          label: "Шингээлтийн танк#5",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        // === Шингээлтийн танк#6 ===
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 48,
          label: "Шингээлтийн танк#6",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Нүүрсний хэмжээ, гр/л",
          type: "TEXT",
          order: 49,
          label: "Шингээлтийн танк#6",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        // === Шингээлтийн танк#6-ын гаралт ===
        {
          title: "Гар PH метрийн заалт",
          type: "TEXT",
          order: 50,
          label: "Шингээлтийн танк#6-ын гаралт",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 51,
          label: "Шингээлтийн танк#6-ын гаралт",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 52,
          label: "Шингээлтийн танк#6-ын гаралт",
          allowedHours: [6, 8, 10, 12, 14, 16, 18, 20, 22, 0, 2, 4],
        },
        // === Нүүрс дамжуулсан эсэх ===
        {
          title: "Шингээлтийн танк 1-ээс хүчлээр угаах баганаруу",
          type: "BOOLEAN",
          order: 53,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Шингээлтийн танк 2-оос шингээх танк 1-рүү",
          type: "BOOLEAN",
          order: 54,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Шингээлтийн танк 3-аас шингээх танк 2-руу",
          type: "BOOLEAN",
          order: 55,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Шингээлтийн танк 4-өөс шингээх танк 3-руу",
          type: "BOOLEAN",
          order: 56,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Шингээлтийн танк 5-аас шингээх танк 4-рүү",
          type: "BOOLEAN",
          order: 57,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Шингээлтийн танк 6-аас шингээх танк 5-руу",
          type: "BOOLEAN",
          order: 58,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Нүүрс сэргээх зуунаас шингээлтийн 6-р танкруу",
          type: "BOOLEAN",
          order: 59,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Шинэ нүүрсний танкнаас шингээлтийн 6-р танкруу",
          type: "BOOLEAN",
          order: 60,
          label: "Нүүрс дамжуулсан эсэх",
          allowedHours: [],
        },
        {
          title: "Нэмэлт мэдээлэл",
          type: "TEXT",
          order: 61,
          label: null,
          allowedHours: [],
        },
      ],
    },
    {
      name: "1008 1009",
      questions: [
        {
          title: "Гаралтын хатуулаг %",
          type: "TEXT",
          order: 1,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Халианы усны насосны хурд, %",
          type: "TEXT",
          order: 2,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Гаралтын насосны хурд, % ",
          type: "TEXT",
          order: 3,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "рH зоондын заалт ",
          type: "TEXT",
          order: 4,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Bed mass sensor, kPa",
          type: "TEXT",
          order: 5,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Bed level sensor, м",
          type: "TEXT",
          order: 6,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Мушгилтын момент, МPa",
          type: "TEXT",
          order: 7,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Флокулянтын процент, %",
          type: "TEXT",
          order: 8,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Флокулянтын дозын насосын хурд, л/цаг",
          type: "TEXT",
          order: 9,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Халианы усны FreeCN, ppm",
          type: "TEXT",
          order: 10,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Халианы усны pH",
          type: "TEXT",
          order: 11,
          label: "Өтгөрүүлэгч",
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 12,
          label: "Технологийн ус",
        },
        {
          title: "pH",
          type: "TEXT",
          order: 13,
          label: "Технологийн ус",
        },
        {
          title: "pH",
          type: "TEXT",
          order: 14,
          label: "Хоргүйжүүлэхийн тэжээл ",
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 15,
          label: "Хоргүйжүүлэхийн тэжээл ",
        },
        {
          title: "Solids, %",
          type: "TEXT",
          order: 16,
          label: "Хоргүйжүүлэхийн тэжээл ",
        },
        {
          title: "Гар рH метрийн заалт",
          type: "TEXT",
          order: 17,
          label: "Хоргүйжүүлэх танк#1",
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 18,
          label: "Хоргүйжүүлэх танк#1",
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 19,
          label: "Хоргүйжүүлэх танк#1",
        },
        {
          title: "Метабисульфитын урсгал, м3/ц",
          type: "TEXT",
          order: 20,
          label: "Хоргүйжүүлэх танк#1",
        },
        {
          title: "Зэсийн сульфатын урсгал, л/ц",
          type: "TEXT",
          order: 21,
          label: "Хоргүйжүүлэх танк#1",
        },
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 22,
          label: "Хоргүйжүүлэх танк#1",
        },
        {
          title: "Гар рH метрийн заалт",
          type: "TEXT",
          order: 23,
          label: "Хоргүйжүүлэх танк#2",
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 24,
          label: "Хоргүйжүүлэх танк#2",
        },
        {
          title: "DO метрийн заалт, мг/л",
          type: "TEXT",
          order: 25,
          label: "Хоргүйжүүлэх танк#2",
        },
        {
          title: "Хатуулаг, %",
          type: "TEXT",
          order: 26,
          label: "Хоргүйжүүлэх танк#2",
        },
        {
          title: "Free CN ppm",
          type: "TEXT",
          order: 27,
          label: "Филтер пресс (шүүсэн ус)",
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 28,
          label: "Усны урсгал хэмжигч Цэвэршүүлсэн ус 3001-FIT-1, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 29,
          label: "Усны урсгал хэмжигч Цэвэршүүлсэн ус 3001-FIT-1, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 30,
          label: "Урвуу осмос хаягдал 3001-FIT-2, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 31,
          label: "Урвуу осмос хаягдал 3001-FIT-2, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 32,
          label: "3003-ТК-1 ахуйн ус 3001-FIT-3, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 33,
          label: "3003-ТК-1 ахуйн ус 3001-FIT-3, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 34,
          label: "3004-TK-01Жийрэг ус 3001-FIT-4, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 35,
          label: "3004-TK-01Жийрэг ус 3001-FIT-4, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 36,
          label: "Урвалж найруулах 3001-FIT-5, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 37,
          label: "Урвалж найруулах 3001-FIT-5, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 38,
          label: "1011 тэжээл 3001-FIT-6, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 39,
          label: "1011 тэжээл 3001-FIT-6, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 40,
          label: "3001-TK-001, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 41,
          label: "3001-TK-001, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 42,
          label: "3001-TK-002, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 43,
          label: "3001-TK-002, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 44,
          label: "3001-TK-002, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 45,
          label: "3001-TK-002, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 46,
          label: "1009-FIT-1, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 47,
          label: "1009-FIT-1, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Эхлэл",
          type: "TEXT",
          order: 48,
          label: "1009-FIT-2, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Төгсгөл",
          type: "TEXT",
          order: 49,
          label: "1009-FIT-2, м3",
          allowedHours: [5, 17],
        },
        {
          title: "Нэмэлт мэдээлэл",
          type: "TEXT",
          order: 50,
          label: null,
        },
      ],
    },
    {
      name: "1010",
      questions: [
        {
          title: "Ниит шахсан циклийн тоо",
          type: "NUMBER",
          order: 1,
          label: null,
        },
        {
          title: "Нэмэлт мэдээлэл",
          type: "TEXT",
          order: 2,
          label: null,
        },
        // {
        //   title: "Шахалтын дугаар",
        //   type: "NUMBER",
        //   order: 1,
        //   label: null,
        // },
        // {
        //   title: "Эхэлсэн цаг",
        //   type: "TEXT",
        //   order: 2,
        //   label: null,
        // },
        // {
        //   title: "Дууссан цаг",
        //   type: "TEXT",
        //   order: 3,
        //   label: null,
        // },
        // {
        //   title: "PP-001",
        //   type: "TEXT",
        //   order: 4,
        //   label: "Зутангийн насос",
        // },
        // {
        //   title: "PP-002",
        //   type: "TEXT",
        //   order: 5,
        //   label: "Зутангийн насос",
        // },
        // {
        //   title: "FL-001",
        //   type: "TEXT",
        //   order: 6,
        //   label: "Пресс фильтр",
        // },
        // {
        //   title: "FL-002",
        //   type: "TEXT",
        //   order: 7,
        //   label: "Пресс фильтр",
        // },
        // {
        //   title: "Агаарын даралт, кПа",
        //   type: "TEXT",
        //   order: 8,
        //   label: null,
        // },
        // {
        //   title: "Насосны даралт, кПа",
        //   type: "TEXT",
        //   order: 9,
        //   label: null,
        // },
        // {
        //   title: "Усны даралт, кПа",
        //   type: "TEXT",
        //   order: 10,
        //   label: null,
        // },
      ],
    },
    //   {
    //     name: "1011",
    //     questions: [
    //       {
    //         title: "Tank Level(LIT051), %",
    //         type: "TEXT",
    //         order: 1,
    //         label: "ELUATE",
    //       },
    //       {
    //         title: "%Cyanide",
    //         type: "TEXT",
    //         order: 2,
    //         label: "ELUATE",
    //       },
    //       {
    //         title: "%Sodium Hydroxide",
    //         type: "TEXT",
    //         order: 3,
    //         label: "ELUATE",
    //       },
    //       {
    //         title: "Harvest Batch No.",
    //         type: "TEXT",
    //         order: 4,
    //         label: "LOADED CARBON",
    //       },
    //       {
    //         title: "Acid soaking",
    //         type: "TEXT",
    //         order: 5,
    //         label: "LOADED CARBON",
    //       },
    //       {
    //         title: "C Transfer Flowrate to Elution  m3/h",
    //         type: "TEXT",
    //         order: 6,
    //         label: "LOADED CARBON",
    //       },
    //       {
    //         title: "C Transfer Flowrate to Regen. Kiln m3/h",
    //         type: "TEXT",
    //         order: 7,
    //         label: "LOADED CARBON",
    //       },
    //       {
    //         title: "Solution Heater",
    //         type: "TEXT",
    //         order: 8,
    //         label: "ELUTION",
    //       },
    //       {
    //         title: "Eluate Flowrate FIT010, m3/h",
    //         type: "TEXT",
    //         order: 9,
    //         label: "ELUTION",
    //       },
    //       {
    //         title: "Column Pressure PT004, kPa",
    //         type: "TEXT",
    //         order: 10,
    //         label: "ELUTION",
    //       },
    //       {
    //         title: "Heater Feed Temp. TT230, °C",
    //         type: "TEXT",
    //         order: 11,
    //         label: "ELUTION",
    //       },
    //       {
    //         title: "Column Feed Temp. TT017, °C",
    //         type: "TEXT",
    //         order: 12,
    //         label: "ELUTION",
    //       },
    //       {
    //         title: "F3 Inlet Press., kPa  Analog V108",
    //         type: "TEXT",
    //         order: 13,
    //         label: "RECOVERY HEAT EXCHANGER HX-001",
    //       },
    //       {
    //         title: "F2 Outlet Press., kPa  Analog V42",
    //         type: "TEXT",
    //         order: 14,
    //         label: "RECOVERY HEAT EXCHANGER HX-001",
    //       },
    //       {
    //         title: "F1 Inlet Press., kPa  Analog V24",
    //         type: "TEXT",
    //         order: 15,
    //         label: "RECOVERY HEAT EXCHANGER HX-001",
    //       },
    //       {
    //         title: "F4 Outlet Press., kPa  Analog V29",
    //         type: "TEXT",
    //         order: 16,
    //         label: "RECOVERY HEAT EXCHANGER HX-001",
    //       },
    //       {
    //         title: "F1 Inlet Press., kPa  Analog V32",
    //         type: "TEXT",
    //         order: 17,
    //         label: "TRIM HEAT EXCHANGER HX-002",
    //       },
    //       {
    //         title: "F4 Outlet Press., kPa  Analog V35",
    //         type: "TEXT",
    //         order: 18,
    //         label: "TRIM HEAT EXCHANGER HX-002",
    //       },
    //       {
    //         title: "Inlet Press., kPa  Analog V45",
    //         type: "TEXT",
    //         order: 19,
    //         label: "ELUATE HEATER HE-001",
    //       },
    //       {
    //         title: "Outlet Press., kPa Analog V46",
    //         type: "TEXT",
    //         order: 20,
    //         label: "ELUATE HEATER HE-001",
    //       },
    //       {
    //         title: "RC-001 Voltage (V)",
    //         type: "TEXT",
    //         order: 21,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "RC-001 Ampere (A)",
    //         type: "TEXT",
    //         order: 22,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "RC-002 Voltage (V)",
    //         type: "TEXT",
    //         order: 23,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "RC-002 Ampere (A)",
    //         type: "TEXT",
    //         order: 24,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "Pregnant Solution Au, ppm",
    //         type: "TEXT",
    //         order: 25,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "Pregnant Solution Ag, ppm",
    //         type: "TEXT",
    //         order: 26,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "Barren Solution Au, ppm",
    //         type: "TEXT",
    //         order: 27,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "Barren Solution Ag, ppm",
    //         type: "TEXT",
    //         order: 28,
    //         label: "EW RECTIFIERS",
    //       },
    //       {
    //         title: "1011-PS-001 (Acid Column PS)",
    //         type: "TEXT",
    //         order: 29,
    //         label: "SUMP PUMPS",
    //       },
    //       {
    //         title: "1011-PS-002 (Elution Column PS)",
    //         type: "TEXT",
    //         order: 30,
    //         label: "SUMP PUMPS",
    //       },
    //       {
    //         title: "Tank Level",
    //         type: "TEXT",
    //         order: 31,
    //         label: "DIESEL",
    //       },
    //       {
    //         title: "5001-PP-001",
    //         type: "TEXT",
    //         order: 32,
    //         label: "DIESEL",
    //       },
    //       {
    //         title: "5001-PP-002",
    //         type: "TEXT",
    //         order: 33,
    //         label: "DIESEL",
    //       },
    //     ],
    //   },
  ];

  for (const dept of departments) {
    const department = await prisma.department.upsert({
      where: { name: dept.name },
      update: {},
      create: { name: dept.name },
    });

    for (const q of dept.questions) {
      await prisma.question.upsert({
        where: {
          title_departmentId: {
            title: q.title,
            departmentId: department.id,
          },
        },
        update: { order: q.order, allowedHours: (q as any).allowedHours ?? [] },
        create: {
          title: q.title,
          type: q.type as any,
          order: q.order,
          label: q.label,
          allowedHours: (q as any).allowedHours ?? [],
          departmentId: department.id,
        },
      });
    }

    console.log(
      `✓ ${dept.name} seeded with ${dept.questions.length} questions`,
    );
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
